# %% [markdown]
# The Webster-Horn equation is an adiabatic 1D reduction of the Laplace-Neumann
# eigenproblem on a body of revolution: at each axial station the transverse
# shape is the local disk mode J_m(j'_{m,l} * r / R(z)), and its slowly-varying
# amplitude A(z) solves a cheap 1D horn eigenproblem per (m, l) branch. This
# pipeline computes the approximate harmonics represented on the 2D meridian
# mesh (like the exact axisymmetric case), reconstructs the 3D basis by
# revolution, and decomposes gene expression data against it.

# %%
import os
import numpy as np
import pyvista as pv
import matplotlib.pyplot as plt

from embryoharmonics import Harmonics
from embryoharmonics import celegans
from embryoharmonics.celegans import compute_webster_horn_meridian_harmonics

# %%
ROOT = os.path.join(os.getcwd(), 'tests', 'resources')
MODEL_PATH = os.path.join(ROOT, 'celegans_models.h5')
# A directory of parquet files (e.g. 'data/cpm-20260828') works here as well
GENE_PATH = os.path.join(ROOT, 'celegans_genedata.h5')
pv.set_jupyter_backend('client')

# %%
TIME_STEP = 420
embryo_model_loader = celegans.EmbryoModelLoader(MODEL_PATH)
embryo_model = embryo_model_loader.load(TIME_STEP, symmetric=True)
meridian_mesh = embryo_model.generate_meridian_mesh(mesh_size=5)
print(f"Number of elements: {meridian_mesh.n_cells}")

plotter = pv.Plotter()
plotter.add_mesh(meridian_mesh, show_edges=True)
plotter.view_xz()
plotter.show()

# %%
# Compute the first few Webster-Horn harmonics; each mode carries an exact
# (m, l, n) label, and m > 0 modes come in degenerate cos/sin pairs
N = 30
horn, labels = compute_webster_horn_meridian_harmonics(meridian_mesh, embryo_model, n=N)

# %%
# Visualize the meridian part of the first few modes with their labels
for i in range(6):
    plotter = pv.Plotter()
    plotter.add_mesh(meridian_mesh.copy(), scalars=horn[i].data, cmap='turbo')
    plotter.add_text(
        f"eigenvalue {horn.eigenvalues[i]:.2e}, "
        f"(m, l, n)={labels[i]} ({horn.trig_kinds[i]})",
        font_size=12,
    )
    plotter.view_xz()
    plotter.show()

# %%
# The approximation is good but not exact: compare the eigenvalues with a full
# 3D FEM solve on the symmetric embryo mesh
mesh_3d = embryo_model.generate_mesh(mesh_size=5)
harmonics_3d = Harmonics.compute(mesh_3d, n=N)

plt.scatter(range(N), harmonics_3d.eigenvalues, label="3D FEM", marker='o')
plt.scatter(range(N), horn.eigenvalues[:N], label="Webster-Horn", marker='x')
plt.legend()
plt.title("Eigenvalue spectra")
plt.xlabel("# harmonic")
plt.ylabel("eigenvalue")
plt.show()

# %%
# The 3D basis is reconstructed as v(r, z) * cos/sin(m * theta), either on a
# given mesh or on a fresh mesh generated by revolving the meridian mesh
full = horn.to_full_3d(mesh_3d)
# full = horn.to_full_3d(mesh_size=5)  # revolve the meridian mesh

# Slice through an m > 0 mode to see the angular dependence
mode = int(np.flatnonzero(horn.angular_orders > 0)[0])
mesh_3d["harmonic"] = full[mode].data
plotter = pv.Plotter()
plotter.add_mesh(mesh_3d.slice_along_axis(n=10, axis="z"), scalars="harmonic", cmap='turbo')
plotter.show()
mesh_3d.clear_data()

# %%
# Gene expression data is decomposed against the reconstructed 3D basis
GENE_NAME = "cwn-1"
gene_data_loader = celegans.open_gene_data_loader(GENE_PATH)
gene_data = gene_data_loader.load(GENE_NAME, TIME_STEP)

# TODO: there is a mismatch between the scales of the geometry and the gene data
#   (about a factor of 5) - fix this in a general way!
# If the factor is chosen too large, some points are outside the domain
gene_data.locations *= 5

mesh_data = gene_data.interpolate(full.mesh)
coefficients = full.decompose(mesh_data)[GENE_NAME]

# %%
# The angular labels show how much of the gene pattern is rotationally
# symmetric (m = 0) versus angularly structured (m > 0)
plt.scatter(
    range(len(full)), np.abs(coefficients),
    c=horn.angular_orders, cmap='tab10'
)
plt.gca().set_yscale('log')
plt.colorbar(label="azimuthal order m")
plt.title(f"Eigen coefficients of {GENE_NAME}")
plt.xlabel("# harmonic")
plt.ylabel("coefficient")
plt.show()

# %%
