name: embryo-harmonics
channels:
  - conda-forge
dependencies:
  - python ==3.10
  - h5py
  - numpy
  - scipy
  - matplotlib
  - pyvista
  - jupyter
  - jupytext
  - pip
  - pip:
    - ngsolve
    - webgui_jupyter_widgets
