name: embryo-harmonics
channels:
  - conda-forge
dependencies:
  - python==3.12
  - h5py
  - numpy==2.2.0
  - scipy
  - matplotlib
  - pytest
  - pytest-cov
  - pyvista==0.44.2 
  - trame
  - trame-vtk
  - trame-vuetify
  - tqdm
  - jupyter
  - jupytext
  - pip
  - pip:
    - ngsolve==6.2.2406
    - webgui_jupyter_widgets
    - -e .
