"""Reconstruct 3D harmonic fields on an embryo mesh from the Webster-Horn
approximation, so they can be compared with :class:`Harmonics` computed
directly on the mesh (same mesh, same mass-normalization convention).
"""
import logging

import numpy as np
import pyvista as pv
import scipy.sparse as scs
from scipy.special import jv

from embryoharmonics.celegans.embryo_model import EmbryoModel, axial_profile
from embryoharmonics.fem import FemMatrices
from embryoharmonics.harmonics import Harmonics
from embryoharmonics.webster_horn import jp_zero, webster_envelopes


_logger = logging.getLogger(__name__)


def compute_webster_horn_harmonics(
        mesh: pv.UnstructuredGrid,
        embryo_model: EmbryoModel,
        *,
        n: int = 10,
        n_samples: int = 200,
) -> tuple[Harmonics, list[tuple[int, int, int]]]:
    """Approximate the first ``n`` harmonics of a (rotationally symmetric)
    embryo mesh using the Webster-Horn approximation, reconstructed as fields
    on the given mesh.

    The Webster-Horn equation only separates modes by their (m, l) branch on
    the assumption of an exact body of revolution, so ``embryo_model`` should
    be one loaded with ``symmetric=True``.

    :param mesh: The embryo mesh to reconstruct the fields on (usually the
        mesh generated from ``embryo_model``, but any mesh occupying roughly
        the same region works, since the modes are evaluated analytically)
    :param embryo_model: The (rotationally symmetric) embryo model providing
        the central axis and radius profile
    :param n: The number of harmonics to approximate; the (m, l) branches
        needed to find the lowest ``n`` modes are included adaptively
    :param n_samples: The number of points to sample the axial profile at
    :return: The approximated harmonics defined on ``mesh``, and their
        ``(m, l, n)`` mode labels (azimuthal order, radial branch, axial
        index). Modes sharing a label form a degenerate cluster.
    """
    s_samples, R_samples, t_samples, z_samples = axial_profile(embryo_model, n_samples)
    candidates = _select_modes(s_samples, R_samples, n)

    s_node, r_node, theta_node, R_node = _node_axial_coordinates(
        mesh, embryo_model, t_samples, s_samples, R_samples, z_samples
    )

    mass = FemMatrices.compute_for(mesh, stiffness=False).mass

    fields = np.empty((len(candidates), mesh.n_points))
    eigenvalues = np.empty(len(candidates))
    for i, candidate in enumerate(candidates):
        field = _reconstruct_field(candidate, s_samples, s_node, r_node, theta_node, R_node)
        # sparse-dense matmul spuriously raises div/overflow FP warnings on some
        # BLAS backends even though the (verified finite) result is unaffected.
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            field /= np.sqrt(field @ (mass @ field))
        fields[i] = field
        eigenvalues[i] = candidate["eigenvalue"]

    labels = [(c["m"], c["l"], c["n"]) for c in candidates]
    orthonormalize_clusters(fields, degenerate_clusters(labels), mass)

    return Harmonics(mesh, fields, eigenvalues), labels


def compute_webster_horn_meridian_harmonics(
        mesh: pv.UnstructuredGrid,
        embryo_model: EmbryoModel,
        *,
        n: int = 10,
        angular_order: int | None = None,
        n_samples: int = 200,
) -> tuple["AxisymmetricHarmonics", list[tuple[int, int, int]]]:
    """Approximate the first ``n`` harmonics of a (rotationally symmetric)
    embryo via the Webster-Horn equation, represented on its 2D meridian mesh.

    The returned object mirrors :class:`AxisymmetricHarmonics.compute`: each
    entry is one 3D mode with meridian field A(s) * J_m(j'_{m,l} * r / R(s))
    and angular factor cos/sin(m * theta), so saving, plotting, and
    :meth:`to_full_3d` reconstruction work unchanged.

    :param mesh: The meridian triangle mesh with points (r, 0, z), as
        generated by :meth:`EmbryoModel.generate_meridian_mesh`
    :param embryo_model: The (rotationally symmetric) embryo model providing
        the central axis and radius profile
    :param n: The number of harmonics to approximate, with the (m, l) branches
        needed to find the lowest ``n`` modes included adaptively; if
        ``angular_order`` is given, the number of modes of that branch
    :param angular_order: If given, compute only this azimuthal branch m: the
        n lowest modes across its radial branches, one entry per mode ('cos'
        only; the degenerate 'sin' partners are not duplicated)
    :param n_samples: The number of points to sample the axial profile at
    :return: The approximate harmonics on the meridian mesh, and their
        ``(m, l, n)`` mode labels (azimuthal order, radial branch, axial index)
    """
    from embryoharmonics.celegans.axisymmetric import AxisymmetricHarmonics

    s_samples, R_samples, _, z_samples = axial_profile(embryo_model, n_samples)
    if angular_order is None:
        candidates = _select_modes(s_samples, R_samples, n)
    else:
        candidates = _branch_modes(s_samples, R_samples, n, angular_order)

    r_node = mesh.points[:, 0]
    s_node = np.interp(mesh.points[:, 2], z_samples, s_samples)
    R_node = np.interp(mesh.points[:, 2], z_samples, R_samples)
    theta_node = np.zeros_like(r_node)

    # The meridian field is shared by a cos/sin pair, so the angular factor is
    # dropped (trig "none") when evaluating
    fields = np.array([
        _reconstruct_field(
            {**c, "trig": "none"}, s_samples, s_node, r_node, theta_node, R_node
        )
        for c in candidates
    ])

    harmonics = AxisymmetricHarmonics(
        mesh,
        fields,
        np.array([c["eigenvalue"] for c in candidates]),
        np.array([c["m"] for c in candidates]),
        np.array(["cos" if c["trig"] == "none" else c["trig"] for c in candidates]),
    )
    return harmonics, [(c["m"], c["l"], c["n"]) for c in candidates]


def _branch_modes(
        s_samples: np.ndarray,
        R_samples: np.ndarray,
        n: int,
        m: int
) -> list[dict]:
    """The n lowest Webster-Horn modes of a single azimuthal order m, drawn
    from as many radial branches l = 1, 2, ... as needed, without cos/sin
    duplication.
    """
    candidates = []
    l = 1
    while True:
        eigenvalues, envelopes = webster_envelopes(s_samples, R_samples, m, l)
        # the lowest eigenvalue of a branch grows with l, so no later branch
        # can contribute either
        if len(candidates) == n and eigenvalues[0] > candidates[-1]["eigenvalue"]:
            return candidates
        jp = jp_zero(m, l)
        for idx in range(min(n, len(eigenvalues))):
            candidates.append({
                "eigenvalue": eigenvalues[idx],
                "m": m,
                "l": l,
                "n": idx,
                "jp": jp,
                "envelope": envelopes[:, idx],
                "trig": "none",
            })
        candidates = sorted(candidates, key=lambda c: c["eigenvalue"])[:n]
        l += 1


def orthonormalize_clusters(
        fields: np.ndarray,
        clusters: list[list[int]],
        mass: scs.csr_matrix
) -> np.ndarray:
    """Mass-orthonormalize the modes within each degenerate cluster, in place.

    The cos/sin pair of a degenerate cluster is mass-orthogonal on an exactly
    rotationally symmetric domain, but a tetrahedral mesh never is -- and
    resampling a basis onto another mesh destroys orthonormality outright. Any
    rotation within a degenerate eigenspace is still an eigenbasis, so this costs
    nothing, and it is what lets :func:`match_modes` compute the projection onto
    a cluster as a plain sum of squared coefficients.

    Modes in different clusters are left alone; only orthonormality *within* each
    cluster is required.

    :param fields: The modes, one per row
    :param clusters: The degenerate clusters, from :func:`degenerate_clusters`
    :param mass: The mass matrix of the mesh the modes are defined on
    :return: ``fields``, modified in place
    """
    # The sparse-dense matmuls raise spurious FP warnings on some BLAS backends
    # even though the (verified finite) result is unaffected.
    with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
        for indices in clusters:
            for position, i in enumerate(indices):
                for j in indices[:position]:
                    fields[i] -= (fields[i] @ (mass @ fields[j])) * fields[j]
                fields[i] /= np.sqrt(fields[i] @ (mass @ fields[i]))
    return fields


def degenerate_clusters(
        labels: list[tuple[int, int, int]]
) -> list[list[int]]:
    """Group mode indices by their ``(m, l, n)`` label.

    Modes with the same label are degenerate: for ``m > 0`` the ``cos(m*theta)``
    and ``sin(m*theta)`` modes share an eigenvalue, so any rotation of the pair
    is an equally valid eigenbasis. Only quantities computed per cluster are
    well defined; individual modes within a cluster are not.

    :param labels: The mode labels, as returned by
        :func:`compute_webster_horn_harmonics`
    :return: One list of mode indices per cluster, in ascending eigenvalue order
    """
    clusters = {}
    for index, label in enumerate(labels):
        clusters.setdefault(label, []).append(index)
    return sorted(clusters.values(), key=lambda indices: indices[0])


def match_modes(
        coefficients: np.ndarray,
        clusters: list[list[int]]
) -> tuple[np.ndarray, np.ndarray]:
    """Pair every target mode one-to-one with the approximate eigenfunction it
    matches best, and return that scalar product.

    ``coefficients[i, j]`` is the mass-weighted scalar product of approximate
    mode ``i`` with target mode ``j``, i.e. the output of
    :meth:`Harmonics.decompose` stacked column-wise, with both bases
    mass-normalized.

    For a degenerate cluster ``C`` there is no single approximate mode to pair
    with: for m > 0 the pair ``cos(m*theta)``, ``sin(m*theta)`` spans a 2D
    eigenspace, and every rotation ``cos(m*(theta - phi))`` in it is equally an
    eigenfunction -- the phase is gauge, not part of the approximation. The
    best-matching eigenfunction of that cluster is therefore the normalized
    projection ``P_C u / ||P_C u||``, whose scalar product with ``u`` is
    ``||P_C u|| = sqrt(sum_i in C  coefficients[i, j]^2)``. For a
    non-degenerate cluster this reduces to the plain scalar product
    ``|coefficients[i, j]|``.

    :param coefficients: The scalar products of the target basis with respect to
        the approximate basis
    :param clusters: The degenerate clusters of the approximate basis, from
        :func:`degenerate_clusters`
    :return: For each target mode, the index of the matched cluster and the
        scalar product with the best eigenfunction in it (1 means the target
        mode is reproduced exactly)
    """
    # Scalar product of every target mode with the best eigenfunction of every
    # cluster, i.e. the norm of its projection onto that cluster's eigenspace.
    scores = np.array([
        np.linalg.norm(coefficients[indices, :], axis=0) for indices in clusters
    ])
    matched = scores.argmax(axis=0)
    return matched, scores[matched, np.arange(coefficients.shape[1])]


def _select_modes(
        s_samples: np.ndarray,
        R_samples: np.ndarray,
        n: int
) -> list[dict]:
    """Solve the Webster-Horn equation for as many (m, l) branches as needed
    and pick the lowest ``n`` modes overall, expanding m > 0 branches into
    their degenerate cos/sin pair.
    """
    candidates = []
    cutoff = np.inf
    m = 0
    while True:
        branch = _branch_modes(s_samples, R_samples, n, m)
        # the lowest eigenvalue of a branch grows with m, so no later one can
        # contribute either
        if branch[0]["eigenvalue"] > cutoff:
            break
        for c in branch:
            for trig in ("none",) if m == 0 else ("cos", "sin"):
                candidates.append({**c, "trig": trig})
        candidates.sort(key=lambda c: c["eigenvalue"])
        if len(candidates) >= n:
            cutoff = candidates[n - 1]["eigenvalue"]
        m += 1

    # Never split a degenerate cos/sin pair across the truncation boundary:
    # a half-cluster would make cluster-wise comparisons meaningless.
    selected = candidates[:n]
    label = lambda c: (c["m"], c["l"], c["n"])
    while len(selected) < len(candidates) and label(candidates[len(selected)]) == label(selected[-1]):
        selected.append(candidates[len(selected)])
    if len(selected) > n:
        _logger.info(
            "Extended to %d modes to keep the degenerate cluster %s intact",
            len(selected), label(selected[-1])
        )
    return selected


def _node_axial_coordinates(
        mesh: pv.UnstructuredGrid,
        embryo_model: EmbryoModel,
        t_samples: np.ndarray,
        s_samples: np.ndarray,
        R_samples: np.ndarray,
        z_samples: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Compute the (arclength, radius, angle, local worm radius) cylindrical
    coordinates of every mesh node relative to the embryo model's central
    axis.
    """
    t_node = np.interp(mesh.points[:, 2], z_samples, t_samples)
    central_node = embryo_model.central_spline(t_node)

    radial = mesh.points[:, :2] - central_node[:, :2]
    r_node = np.linalg.norm(radial, axis=1)
    theta_node = np.arctan2(radial[:, 1], radial[:, 0])

    s_node = np.interp(t_node, t_samples, s_samples)
    R_node = np.interp(t_node, t_samples, R_samples)

    return s_node, r_node, theta_node, R_node


def _reconstruct_field(
        candidate: dict,
        s_samples: np.ndarray,
        s_node: np.ndarray,
        r_node: np.ndarray,
        theta_node: np.ndarray,
        R_node: np.ndarray,
) -> np.ndarray:
    """Reconstruct a single Webster-Horn mode as a field on the mesh nodes:
    ``A(s) * J_m(j'_{m,l} * r / R(s)) * cos_or_sin(m * theta)``.
    """
    amplitude = np.interp(s_node, s_samples, candidate["envelope"])

    bessel_argument = np.divide(
        candidate["jp"] * r_node, R_node,
        out=np.zeros_like(r_node), where=R_node > 1e-12
    )
    profile = jv(candidate["m"], bessel_argument)

    match candidate["trig"]:
        case "cos":
            angular = np.cos(candidate["m"] * theta_node)
        case "sin":
            angular = np.sin(candidate["m"] * theta_node)
        case _:
            angular = 1.0

    return amplitude * profile * angular
