# %% [markdown]
# The rotationally symmetric embryo (all transverse splines are rotated copies
# of the 0-th one) is a body of revolution, so its Laplace harmonics separate
# exactly into a meridian part v(r, z) and an angular factor cos/sin(k*theta).
# This pipeline computes the harmonics on a 2D meridian mesh (one cheap
# eigensolve per angular order k), reconstructs the 3D basis by revolution,
# and decomposes gene expression data against it.

# %%
import os
import numpy as np
import pyvista as pv
import matplotlib.pyplot as plt

from embryoharmonics import Harmonics
from embryoharmonics import celegans
from embryoharmonics.celegans import AxisymmetricHarmonics

# %%
ROOT = os.path.join(os.getcwd(), 'tests', 'resources')
MODEL_PATH = os.path.join(ROOT, 'celegans_models.h5')
GENE_PATH = os.path.join(ROOT, 'celegans_genedata.h5')
pv.set_jupyter_backend('client')

# %%
TIME_STEP = 420
embryo_model_loader = celegans.EmbryoModelLoader(MODEL_PATH)
embryo_model = embryo_model_loader.load(TIME_STEP, symmetric=True)
meridian_mesh = embryo_model.generate_meridian_mesh(mesh_size=5)
print(f"Number of elements: {meridian_mesh.n_cells}")

plotter = pv.Plotter()
plotter.add_mesh(meridian_mesh, show_edges=True)
plotter.view_xz()
plotter.show()

# %%
# Compute the first few harmonics; the angular orders k = 0, 1, ... are solved
# one by one, and modes with k > 0 come in degenerate cos/sin pairs
N = 30
axisymmetric = AxisymmetricHarmonics.compute(meridian_mesh, n=N)

# %%
# Visualize the meridian part of the first few modes; nodal counting yields
# approximate radial/axial "quantum numbers" complementing the exact k
n_radial, n_axial = axisymmetric.nodal_counts()
for i in range(6):
    plotter = pv.Plotter()
    plotter.add_mesh(
        meridian_mesh.copy(), scalars=axisymmetric[i].data, cmap='turbo'
    )
    plotter.add_text(
        f"eigenvalue {axisymmetric.eigenvalues[i]:.2e}, "
        f"k={axisymmetric.angular_orders[i]} ({axisymmetric.trig_kinds[i]}), "
        f"n_r={n_radial[i]}, n_z={n_axial[i]}",
        font_size=12,
    )
    plotter.view_xz()
    plotter.show()

# %%
# The reduction is exact: the eigenvalues coincide with a full 3D FEM solve on
# the symmetric embryo mesh (up to discretization error)
mesh_3d = embryo_model.generate_mesh(mesh_size=5)
harmonics_3d = Harmonics.compute(mesh_3d, n=N)

plt.scatter(range(N), harmonics_3d.eigenvalues, label="3D FEM", marker='o')
plt.scatter(range(N), axisymmetric.eigenvalues[:N], label="2D axisymmetric", marker='x')
plt.legend()
plt.title("Eigenvalue spectra")
plt.xlabel("# harmonic")
plt.ylabel("eigenvalue")
plt.show()

# %%
# The 3D basis is reconstructed as v(r, z) * cos/sin(k * theta), either on a
# given mesh or on a fresh mesh generated by revolving the meridian mesh
full = axisymmetric.to_full_3d(mesh_3d)
# full = axisymmetric.to_full_3d(mesh_size=5)  # revolve the meridian mesh

# Slice through a k > 0 mode to see the angular dependence
mode = int(np.flatnonzero(axisymmetric.angular_orders > 0)[0])
mesh_3d["harmonic"] = full[mode].data
plotter = pv.Plotter()
plotter.add_mesh(mesh_3d.slice_along_axis(n=10, axis="z"), scalars="harmonic", cmap='turbo')
plotter.show()
mesh_3d.clear_data()

# %%
# Gene expression data is decomposed against the reconstructed 3D basis
GENE_NAME = "cwn-1"
gene_data_loader = celegans.GeneDataLoader(GENE_PATH)
gene_data = gene_data_loader.load(GENE_NAME, TIME_STEP)

# TODO: there is a mismatch between the scales of the geometry and the gene data
#   (about a factor of 5) - fix this in a general way!
# If the factor is chosen too large, some points are outside the domain
gene_data.locations *= 5

mesh_data = gene_data.interpolate(full.mesh)
coefficients = full.decompose(mesh_data)[GENE_NAME]

# %%
# The angular labels show how much of the gene pattern is rotationally
# symmetric (k = 0) versus angularly structured (k > 0)
plt.scatter(
    range(len(full)), np.abs(coefficients),
    c=axisymmetric.angular_orders, cmap='tab10'
)
plt.gca().set_yscale('log')
plt.colorbar(label="angular order k")
plt.title(f"Eigen coefficients of {GENE_NAME}")
plt.xlabel("# harmonic")
plt.ylabel("coefficient")
plt.show()

# %%
